# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sdnmpi_pb2 as sdnmpi__pb2


class SDNMPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListJob = channel.unary_unary(
        '/SDNMPI/ListJob',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=sdnmpi__pb2.ListJobResponse.FromString,
        )
    self.GetJob = channel.unary_unary(
        '/SDNMPI/GetJob',
        request_serializer=sdnmpi__pb2.GetJobRequest.SerializeToString,
        response_deserializer=sdnmpi__pb2.GetJobResponse.FromString,
        )
    self.CreateJob = channel.unary_unary(
        '/SDNMPI/CreateJob',
        request_serializer=sdnmpi__pb2.CreateJobRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.StartJob = channel.unary_unary(
        '/SDNMPI/StartJob',
        request_serializer=sdnmpi__pb2.StartJobRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FinishJob = channel.unary_unary(
        '/SDNMPI/FinishJob',
        request_serializer=sdnmpi__pb2.FinishJobRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListProcess = channel.unary_unary(
        '/SDNMPI/ListProcess',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=sdnmpi__pb2.ListProcessResponse.FromString,
        )
    self.GetProcess = channel.unary_unary(
        '/SDNMPI/GetProcess',
        request_serializer=sdnmpi__pb2.GetProcessRequest.SerializeToString,
        response_deserializer=sdnmpi__pb2.GetProcessResponse.FromString,
        )
    self.CreateProcess = channel.unary_unary(
        '/SDNMPI/CreateProcess',
        request_serializer=sdnmpi__pb2.CreateProcessRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.StartProcess = channel.unary_unary(
        '/SDNMPI/StartProcess',
        request_serializer=sdnmpi__pb2.StartProcessRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FinishProcess = channel.unary_unary(
        '/SDNMPI/FinishProcess',
        request_serializer=sdnmpi__pb2.FinishProcessRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class SDNMPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinishJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinishProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SDNMPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListJob': grpc.unary_unary_rpc_method_handler(
          servicer.ListJob,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=sdnmpi__pb2.ListJobResponse.SerializeToString,
      ),
      'GetJob': grpc.unary_unary_rpc_method_handler(
          servicer.GetJob,
          request_deserializer=sdnmpi__pb2.GetJobRequest.FromString,
          response_serializer=sdnmpi__pb2.GetJobResponse.SerializeToString,
      ),
      'CreateJob': grpc.unary_unary_rpc_method_handler(
          servicer.CreateJob,
          request_deserializer=sdnmpi__pb2.CreateJobRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'StartJob': grpc.unary_unary_rpc_method_handler(
          servicer.StartJob,
          request_deserializer=sdnmpi__pb2.StartJobRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FinishJob': grpc.unary_unary_rpc_method_handler(
          servicer.FinishJob,
          request_deserializer=sdnmpi__pb2.FinishJobRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ListProcess': grpc.unary_unary_rpc_method_handler(
          servicer.ListProcess,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=sdnmpi__pb2.ListProcessResponse.SerializeToString,
      ),
      'GetProcess': grpc.unary_unary_rpc_method_handler(
          servicer.GetProcess,
          request_deserializer=sdnmpi__pb2.GetProcessRequest.FromString,
          response_serializer=sdnmpi__pb2.GetProcessResponse.SerializeToString,
      ),
      'CreateProcess': grpc.unary_unary_rpc_method_handler(
          servicer.CreateProcess,
          request_deserializer=sdnmpi__pb2.CreateProcessRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'StartProcess': grpc.unary_unary_rpc_method_handler(
          servicer.StartProcess,
          request_deserializer=sdnmpi__pb2.StartProcessRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FinishProcess': grpc.unary_unary_rpc_method_handler(
          servicer.FinishProcess,
          request_deserializer=sdnmpi__pb2.FinishProcessRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SDNMPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
